#!/bin/bash
if [ "$ML_JOB_ID" == "" ] 
then
    echo "\$ML_JOB_ID is undefined. It must hold the oargridsub reservation number for the ML services machines."
    exit 1
fi

if [ "$ML_JOB_KEY_FILE" == "" ] 
then
    echo "\$ML_JOB_KEY_FILE is undefined. It must hold the private key generated by oargridsub."
    exit 1
fi

if [ "$ML_SCRIPTS" == "" ]
then 
    echo "\$ML_SCRIPTS is undefined. It must point to MonALISA deployment scripts dir."
    exit 1
fi

if [ "$ENV_FILE" == "" ]
then 
    echo "\$ENV_FILE is undefined. It must point to the configuration file for the environment that has to be deployed."
    exit 1
fi

