# $Id: Makefile 3995 2008-06-11 02:28:16Z tatebe $

top_builddir = ../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

SCRIPTS = gfdump.postgresql

include $(top_srcdir)/makes/script.mk
