#!/bin/sh

case $# in
2)	:;;
*)	echo "Usage: $0 <source_file> <destination_file>" >&2
	exit 1;;
esac
src=$1
dst=$2

prefix="/Users/vitran/irisawork/Gfarm_blobSeer/gfarm_bin/"
exec_prefix="${prefix}"
libdir="${exec_prefix}/lib"
sysconfdir="${prefix}/etc"

globus_flavor=""

# If Globus is not configured, use "gcc32" for documentation purpose.
: ${globus_flavor:="gcc32"}

INSTALL="/Users/vitran/irisawork/BlobSeer/contrib/gfarm/gfarm-2.1.1_blobseer/makes/install-sh -c"
tmpfile=/tmp/insttmp.$$
status=1

trap 'rm -f $tmpfile; exit $status' 0 1 2 15

if grep '%%' "$src" >/dev/null; then
	sed	-e "s|%%PREFIX%%|$prefix|g" \
		-e "s|%%LIBDIR%%|$libdir|g" \
		-e "s|%%GLOBUS_FLAVOR%%|$globus_flavor|g" \
		$src >$tmpfile
	${INSTALL} -m 644 "$tmpfile" "$dst"
	status=$?
	rm -f $tmpfile
else
	${INSTALL} -m 644 "$src" "$dst"
	status=$?
fi
